# see
#   http://about.travis-ci.org/docs/user/getting-started/
#   http://about.travis-ci.org/docs/user/languages/c/
#   http://about.travis-ci.org/docs/user/build-configuration/
#
language: c
branches:
  only:
    - master
compiler:
  - gcc
  - clang
# Sets up configure, enables maintainer mode and gtk doc
before_script: ./autogen.sh
script: make && make test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gtk-doc-tools
